######################################################################
##
## Filename: cpu_tb.udo
## Created on: Wed Jun 08 0:25:42 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
